name: fvn-dfm
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - numpy
  - pyarrow
  - scikit-learn
  - statsmodels
  - pyyaml
  - requests
  - beautifulsoup4
  - lxml
  - tqdm
  - matplotlib
  - pytest
  - pip
